/// Flutter icons OlmaIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OlmaIcons
///      fonts:
///       - asset: fonts/OlmaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OlmaIcons {
  OlmaIcons._();

  static const _kFontFam = 'OlmaIcons';
  static const _kFontPkg = null;

  static const IconData generarcomunicado = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indicadoresfinancieros = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consulta = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accederproducto = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData presentacionProducto = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData informes = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
